apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opensearch-secret
  namespace: opensearch
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-secretstore
    kind: ClusterSecretStore
  target:
    name: opensearch-admin
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: secret/opensearch
        property: admin-password

